# Generated by Django 4.1.1 on 2022-10-01 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('department', models.CharField(choices=[('Operations', 'Operations'), ('Infocomm technology', 'Infocomm technology'), ('Engineering', 'Engineering'), ('Corportate', 'Corporate')], max_length=100)),
                ('description', models.TextField(blank=True, default='', max_length=600, verbose_name='Description')),
                ('points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, default='', max_length=600, verbose_name='Description')),
                ('quantity', models.IntegerField()),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('points_granted', models.IntegerField()),
                ('status', models.CharField(choices=[('Incomplete', 'Incomplete'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed')], default='Incomplete', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_request', to='main.customuser')),
                ('to_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_request', to='main.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('from_follow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_follow', to='main.customuser')),
                ('to_follow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_follow', to='main.customuser')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='users', to='main.task'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
