# Generated by Django 4.1.1 on 2022-10-01 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, default='', max_length=600, verbose_name='Description')),
                ('quantity', models.IntegerField()),
                ('cost', models.IntegerField()),
            ],
        ),
    ]
