# Generated by Django 4.1.1 on 2022-10-01 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_follow_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='follower',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='following',
        ),
        migrations.AddField(
            model_name='follow',
            name='follower',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='follow', to='main.customuser'),
        ),
        migrations.AddField(
            model_name='follow',
            name='following',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='followed_by', to='main.customuser'),
        ),
    ]
