# Generated by Django 4.1.1 on 2022-10-01 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_follow_follower_alter_follow_following'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='requested_by', to='main.customuser')),
                ('requestor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='request', to='main.customuser')),
            ],
        ),
    ]
