# Generated by Django 4.1.1 on 2022-10-01 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_cart_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='count',
        ),
    ]
