# Generated by Django 4.1.1 on 2022-10-02 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_cart_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='reward',
        ),
        migrations.AddField(
            model_name='cart',
            name='reward',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='main.reward'),
            preserve_default=False,
        ),
    ]
