# Generated by Django 4.1.1 on 2022-10-02 05:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2022, 10, 2, 13, 39, 50, 971947)),
        ),
    ]
