# Generated by Django 4.1.1 on 2022-10-02 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_reward_image_alter_customuser_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reward',
            name='image',
        ),
    ]
